### ISSUE TITLE
On the UI for this endpoint 78.159.113.46 the Policy page displays Error getting Policy data

### ISSUE THREAD

**Issue by NadHodeGW** [k8-proxy/icap-infrastructure#24]
http://78.159.113.46:31829/policy

**Comment by azopat** [comment]
This is solved.
You can check it here : http://78.159.113.47:31829

**Comment by NadHodeGW** [comment]
@azopat, this is not solved, the History screen still displays: Error getting Policy data, please take a look

**Comment by NadHodeGW** [comment]
@azopat, @mahnouman, files processed do not appear in the transaction log for that endpoint above in previous comment
There is a new server i'm using that shows transactions ok but the policy screen still displays error getting Policy data. Can you take a look at that please
http://34.244.23.244:31829/

![image](https://user-images.githubusercontent.com/61200359/105347121-590fb100-5bde-11eb-9b66-688e76a2877e.png)

**Comment by azopat** [comment]
@NadHodeGW  the fix wasn't on that version yet.
Either use the one i sent on this thread or any new one created from ami generated from monday.

**Comment by GINAGC** [comment]
@naderaly I guess this one can be closed?

**Comment by naderaly** [comment]
@GINAGC 
I didn't participate in this issue
